kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jnkhome-pv-claim
  namespace: k8s-bld
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
